[package]
name = "protoc-gen-py-pkg"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
protobuf = "3.7.2"

[build-dependencies]
protobuf = "3.7.2"
protobuf-codegen = "3.7.2"
