# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: examples/v1/foo.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'examples/v1/foo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2
import py_package_pb2 as py__package__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65xamples/v1/foo.proto\x1a google/protobuf/descriptor.proto\x1a\x10py_package.proto\"?\n\x03\x46oo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\x03\x62\x61r\x18\x02 \x01(\x0b\x32\x08.Foo.Bar\x1a\x13\n\x03\x42\x61r\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x13\n\x03\x42\x61r\x12\x0c\n\x04name\x18\x01 \x01(\tB\x0f\x82\xb5\x18\x0b\x65xamples.v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'examples.v1.foo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\202\265\030\013examples.v1'
  _globals['_FOO']._serialized_start=77
  _globals['_FOO']._serialized_end=140
  _globals['_FOO_BAR']._serialized_start=121
  _globals['_FOO_BAR']._serialized_end=140
  _globals['_BAR']._serialized_start=121
  _globals['_BAR']._serialized_end=140
# @@protoc_insertion_point(module_scope)
