// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: py_package.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PyPackageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enable Python package generation.
	Enable bool `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	// If true, imports will be generated at the top level of the package.
	EnableTopLevelImports bool `protobuf:"varint,2,opt,name=enable_top_level_imports,json=enableTopLevelImports,proto3" json:"enable_top_level_imports,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PyPackageOptions) Reset() {
	*x = PyPackageOptions{}
	mi := &file_py_package_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PyPackageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PyPackageOptions) ProtoMessage() {}

func (x *PyPackageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_py_package_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PyPackageOptions.ProtoReflect.Descriptor instead.
func (*PyPackageOptions) Descriptor() ([]byte, []int) {
	return file_py_package_proto_rawDescGZIP(), []int{0}
}

func (x *PyPackageOptions) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *PyPackageOptions) GetEnableTopLevelImports() bool {
	if x != nil {
		return x.EnableTopLevelImports
	}
	return false
}

var file_py_package_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*PyPackageOptions)(nil),
		Field:         1300,
		Name:          "py_package.py_package_opts",
		Tag:           "bytes,1300,opt,name=py_package_opts",
		Filename:      "py_package.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// Python package options.
	//
	// optional py_package.PyPackageOptions py_package_opts = 1300;
	E_PyPackageOpts = &file_py_package_proto_extTypes[0]
)

var File_py_package_proto protoreflect.FileDescriptor

const file_py_package_proto_rawDesc = "" +
	"\n" +
	"\x10py_package.proto\x12\n" +
	"py_package\x1a google/protobuf/descriptor.proto\"c\n" +
	"\x10PyPackageOptions\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x127\n" +
	"\x18enable_top_level_imports\x18\x02 \x01(\bR\x15enableTopLevelImports:c\n" +
	"\x0fpy_package_opts\x12\x1c.google.protobuf.FileOptions\x18\x94\n" +
	" \x01(\v2\x1c.py_package.PyPackageOptionsR\rpyPackageOptsB4Z2github.com/stephenoken/protoc-gen-py-pkg/v1/protosb\x06proto3"

var (
	file_py_package_proto_rawDescOnce sync.Once
	file_py_package_proto_rawDescData []byte
)

func file_py_package_proto_rawDescGZIP() []byte {
	file_py_package_proto_rawDescOnce.Do(func() {
		file_py_package_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_py_package_proto_rawDesc), len(file_py_package_proto_rawDesc)))
	})
	return file_py_package_proto_rawDescData
}

var file_py_package_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_py_package_proto_goTypes = []any{
	(*PyPackageOptions)(nil),         // 0: py_package.PyPackageOptions
	(*descriptorpb.FileOptions)(nil), // 1: google.protobuf.FileOptions
}
var file_py_package_proto_depIdxs = []int32{
	1, // 0: py_package.py_package_opts:extendee -> google.protobuf.FileOptions
	0, // 1: py_package.py_package_opts:type_name -> py_package.PyPackageOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_py_package_proto_init() }
func file_py_package_proto_init() {
	if File_py_package_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_py_package_proto_rawDesc), len(file_py_package_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_py_package_proto_goTypes,
		DependencyIndexes: file_py_package_proto_depIdxs,
		MessageInfos:      file_py_package_proto_msgTypes,
		ExtensionInfos:    file_py_package_proto_extTypes,
	}.Build()
	File_py_package_proto = out.File
	file_py_package_proto_goTypes = nil
	file_py_package_proto_depIdxs = nil
}
