# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: py_package.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'py_package.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10py_package.proto\x12\npy_package\x1a google/protobuf/descriptor.proto\"\\\n\x10PyPackageOptions\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\x12 \n\x18\x65nable_top_level_imports\x18\x02 \x01(\x08\x12\x16\n\x0eparent_package\x18\x03 \x01(\t:T\n\x0fpy_package_opts\x12\x1c.google.protobuf.FileOptions\x18\x94\n \x01(\x0b\x32\x1c.py_package.PyPackageOptionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'py_package_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PYPACKAGEOPTIONS']._serialized_start=66
  _globals['_PYPACKAGEOPTIONS']._serialized_end=158
# @@protoc_insertion_point(module_scope)
