// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc 29.3
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `py_package.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

// @@protoc_insertion_point(message:py_package.PyPackageOptions)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct PyPackageOptions {
    // message fields
    // @@protoc_insertion_point(field:py_package.PyPackageOptions.name)
    pub name: ::std::string::String,
    // @@protoc_insertion_point(field:py_package.PyPackageOptions.enable_top_level_imports)
    pub enable_top_level_imports: bool,
    // special fields
    // @@protoc_insertion_point(special_field:py_package.PyPackageOptions.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a PyPackageOptions {
    fn default() -> &'a PyPackageOptions {
        <PyPackageOptions as ::protobuf::Message>::default_instance()
    }
}

impl PyPackageOptions {
    pub fn new() -> PyPackageOptions {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "name",
            |m: &PyPackageOptions| { &m.name },
            |m: &mut PyPackageOptions| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "enable_top_level_imports",
            |m: &PyPackageOptions| { &m.enable_top_level_imports },
            |m: &mut PyPackageOptions| { &mut m.enable_top_level_imports },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<PyPackageOptions>(
            "PyPackageOptions",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for PyPackageOptions {
    const NAME: &'static str = "PyPackageOptions";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.name = is.read_string()?;
                },
                16 => {
                    self.enable_top_level_imports = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.name);
        }
        if self.enable_top_level_imports != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.name.is_empty() {
            os.write_string(1, &self.name)?;
        }
        if self.enable_top_level_imports != false {
            os.write_bool(2, self.enable_top_level_imports)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> PyPackageOptions {
        PyPackageOptions::new()
    }

    fn clear(&mut self) {
        self.name.clear();
        self.enable_top_level_imports = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static PyPackageOptions {
        static instance: PyPackageOptions = PyPackageOptions {
            name: ::std::string::String::new(),
            enable_top_level_imports: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for PyPackageOptions {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("PyPackageOptions").unwrap()).clone()
    }
}

impl ::std::fmt::Display for PyPackageOptions {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PyPackageOptions {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Extension fields
pub mod exts {

    pub const py_package_opts: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, super::PyPackageOptions> = ::protobuf::ext::ExtFieldOptional::new(1300, ::protobuf::descriptor::field_descriptor_proto::Type::TYPE_MESSAGE);
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10py_package.proto\x12\npy_package\x1a\x20google/protobuf/descriptor\
    .proto\"_\n\x10PyPackageOptions\x12\x12\n\x04name\x18\x01\x20\x01(\tR\
    \x04name\x127\n\x18enable_top_level_imports\x18\x02\x20\x01(\x08R\x15ena\
    bleTopLevelImports:c\n\x0fpy_package_opts\x18\x94\n\x20\x01(\x0b2\x1c.py\
    _package.PyPackageOptions\x12\x1c.google.protobuf.FileOptionsR\rpyPackag\
    eOptsb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(1);
            deps.push(::protobuf::descriptor::file_descriptor().clone());
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(PyPackageOptions::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
